import type { Metadata } from "next";
import "./globals.css";
import Providers from "./provider";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { AuthProvider } from "./_contexts/authcontext";

export const metadata: Metadata = {
  title: "Coordina",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <body className={`antialiased`}>
          <AuthProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            />
            <Providers>{children}</Providers>
          </AuthProvider>
          {/* </ThemeProvider> */}
        </body>
      </head>
    </html>
  );
}
